NUnit homework
limonaaasik/AQA_MTS pull request #13
Opened 2024-01-31 17:32 UTC by limonaaasik

2024-02-05 18:15 UTC, wildpioneer requested changes

2024-02-05 18:15 UTC, wildpioneer commented on NUnit_HW/Calc.cs
> +        internal static int DivInt(int a, int b) => a / b;
Почему методы называются по разному? Повторить тему про перегрузку

2024-02-05 18:15 UTC, wildpioneer commented on NUnit_HW/CalcTest.cs
> +            if (double.IsInfinity((double)2 / 0))
Хочу видеть еще проверку на double.NaN

2024-02-06 07:25 UTC, wildpioneer requested changes

2024-02-06 07:25 UTC, wildpioneer commented on NUnit_HW/CalcTest.cs
> +                Assert.Fail("Ошибка деления на нуль");
А разве эта ветка достижима при жестко заданных значениях как у тебя?

2024-03-03 11:41 UTC, limonaaasik commented
данный пулл-реквест менять не буду.

2024-03-19 13:57 UTC, wildpioneer commented
Проверено

2024-03-19 13:57 UTC, closed without merging