Selenium basic homework
limonaaasik/AQA_MTS pull request #14
Opened 2024-02-07 12:55 UTC by limonaaasik

2024-02-12 21:14 UTC, wildpioneer requested changes

2024-02-12 21:14 UTC, wildpioneer commented on SeleniumBasic/Tests/LaminateTest.cs
> +        IWebElement result1 = Driver.FindElement(By.XPath("//*[contains(text(),'��������� ���������� ������ ��������')]//descendant::span"));
У тебя с кодировкой этого файла проблема - непонятные символы в локаторе

2024-03-03 11:41 UTC, limonaaasik commented
данный пулл-реквест менять не буду.

2024-03-19 13:57 UTC, wildpioneer commented
Проверено

2024-03-19 13:57 UTC, closed without merging