Allure homework
limonaaasik/AQA_MTS pull request #18
Opened 2024-03-03 11:22 UTC by limonaaasik

2024-03-19 14:04 UTC, wildpioneer requested changes

2024-03-19 14:04 UTC, wildpioneer commented on Allure_HW/Tests/BaseTest.cs
> +        Driver.Quit();
только одно замечание - снятие скриншота лучше обернуть в try-catch -  потому как если произойдет exception - то драйвер не закроется

2024-03-28 18:11 UTC, limonaaasik commented
исправлять не буду замечания

2024-04-08 20:58 UTC, closed without merging

2024-04-08 20:58 UTC, wildpioneer commented
Проверено